import { useEffect, useState } from 'react'
import { BarChart3, CheckCircle2, Layers3, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { fetchAnalyticsSummary } from '../api/services.js'

function Metric({ icon: Icon, label, value }) {
  return <article className="rounded-card bg-paper p-5 shadow-card ring-1 ring-black/10"><Icon className="h-5 w-5 text-career" aria-hidden="true"/><p className="mt-4 font-sans text-xs font-bold uppercase tracking-wider text-ink/50">{label}</p><p className="mt-1 font-sans text-3xl font-bold text-ink">{value}</p></article>
}

export default function InternalAnalyticsPage() {
  const [data,setData]=useState(null),[error,setError]=useState('')
  useEffect(()=>{let active=true;fetchAnalyticsSummary().then(value=>{if(active)setData(value)}).catch(err=>{if(active)setError(err.status===403?'This report is restricted to configured administrators.':err.message)});return()=>{active=false}},[])
  return <main className="min-h-screen bg-cream px-4 py-8 text-ink sm:px-6"><div className="mx-auto max-w-5xl"><header className="flex flex-wrap items-center justify-between gap-4"><div><p className="eyebrow text-career">Private aggregate report</p><h1 className="mt-2 display-title text-4xl sm:text-5xl">Daycraft analytics</h1></div><Link to="/dashboard" className="inline-flex min-h-touch items-center rounded-xl bg-ink px-4 font-sans text-sm font-bold text-white">Back to dashboard</Link></header>{error&&<div role="alert" className="mt-8 rounded-card bg-paper p-5 font-sans text-sm text-language ring-1 ring-language/20">{error}</div>}{!data&&!error&&<p role="status" className="mt-8 font-sans text-sm text-ink/60">Loading aggregate metrics…</p>}{data&&<><section aria-label="Current totals" className="mt-8 grid gap-4 sm:grid-cols-3"><Metric icon={Users} label="Current users" value={data.total_users}/><Metric icon={Layers3} label="Current day groups" value={data.total_day_groups}/><Metric icon={CheckCircle2} label="7-day completion" value={`${data.checklist_last_7_days.completion_rate}%`}/></section><div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-card bg-paper p-5 shadow-card ring-1 ring-black/10 sm:p-6"><div className="flex items-center gap-2"><BarChart3 className="h-5 w-5 text-career" aria-hidden="true"/><h2 className="font-sans text-lg font-bold">Events · 30 days</h2></div><dl className="mt-4 divide-y divide-black/10">{Object.entries(data.events_last_30_days).map(([name,total])=><div key={name} className="flex items-center justify-between gap-4 py-3"><dt className="font-mono text-xs text-ink/65">{name}</dt><dd className="font-sans text-sm font-bold">{total}</dd></div>)}</dl></section><section className="rounded-card bg-paper p-5 shadow-card ring-1 ring-black/10 sm:p-6"><h2 className="font-sans text-lg font-bold">Pageviews · 30 days</h2><dl className="mt-4 divide-y divide-black/10">{Object.entries(data.pageviews_last_30_days).map(([path,total])=><div key={path} className="flex items-center justify-between gap-4 py-3"><dt className="font-mono text-xs text-ink/65">{path}</dt><dd className="font-sans text-sm font-bold">{total}</dd></div>)}</dl></section></div></>}</div></main>
}
