import { Link } from 'react-router-dom'
import PublicFooter from '../components/PublicFooter.jsx'

const Section=({title,children})=><section className="mt-9"><h2 className="font-sans text-xl font-bold text-ink sm:text-2xl">{title}</h2><div className="mt-3 space-y-4 font-sans text-body leading-7 text-ink/70 sm:text-base sm:leading-8">{children}</div></section>
const List=({children})=><ul className="list-disc space-y-2 pl-6 marker:text-career">{children}</ul>

export function PrivacyPage(){return <LegalShell title="Privacy Policy" updated="Last updated: August 10, 2026">
  <p>Daycraft is a daily routine and habit planner. This policy explains, in plain language, what information the service handles and why.</p>
  <Section title="Information Daycraft collects"><List>
    <li><strong>Account information:</strong> your name, email address, verification status, and the date you accepted the Terms. Password-based accounts store a one-way password hash, never the readable password.</li>
    <li><strong>Google sign-in information:</strong> when you choose Google, Daycraft receives your Google account identifier, name, and verified email address. Daycraft does not receive your Google password.</li>
    <li><strong>Your routine data:</strong> day groups, weekday assignments, schedule blocks, checklist items, completion logs, reminder preferences, and related settings you create.</li>
    <li><strong>Optional location information:</strong> if you allow browser location access, latitude and longitude are sent to Daycraft to request prayer times. The resulting coordinates and prayer times may be cached by account and date to provide the feature efficiently.</li>
    <li><strong>Technical information:</strong> ordinary server logs may include request times, routes, IP addresses, browser details, and error information needed to secure and operate the service.</li>
  </List></Section>
  <Section title="How information is used"><p>Daycraft uses this information to create and secure your account, synchronize your routines, record checklist progress, send account emails, provide reminders and optional prayer-time information, troubleshoot failures, and prevent misuse.</p></Section>
  <Section title="Privacy-respecting usage analytics"><p>Daycraft uses a first-party analytics system stored in its own PostgreSQL database. It records page paths and a small allow-list of aggregate events: completed signup method, first day-group creation, checklist checks, day-group and account deletion, and notification-permission outcomes.</p><p>Analytics events do not contain names, email addresses, routine titles, checklist labels, schedule descriptions, location, tokens, IP addresses, user-agent strings, or advertising identifiers. Daycraft does not use session recording, heatmaps, third-party analytics pixels, or cross-site tracking. Event-specific one-way deduplication values prevent retry duplicates without storing account IDs or allowing behavior to be joined into individual profiles.</p></Section>
  <Section title="Storage and service providers"><p>Account and routine information is stored in PostgreSQL. Passwords are hashed using Laravel’s secure password hashing tools. Authentication tokens are stored by the browser in localStorage and sent to the API in an authorization header.</p><p>Daycraft relies on infrastructure and service providers where necessary, including email delivery, Google OAuth when selected, and a third-party prayer-time API. These providers receive only the information needed to perform their function.</p></Section>
  <Section title="Cookies and local browser storage"><p>Daycraft does not currently set first-party cookies for normal authentication, preferences, or analytics. It uses localStorage for the sign-in token and limited interface state. Google may use cookies on Google’s own pages during Google sign-in under Google’s policies.</p><p>Because Daycraft does not currently use non-essential cookies, no cookie-consent banner is shown. If cookie-based analytics or advertising is introduced later, appropriate notice and consent will be added first.</p></Section>
  <Section title="Sharing and sale"><p>Daycraft does not sell personal information. Information is shared only with service providers needed to run requested features, when required by law, or when necessary to protect users and the service.</p></Section>
  <Section title="Keeping and deleting data"><p>Information is kept while your account remains active and as reasonably necessary to operate and secure Daycraft. You can permanently delete your account from the dashboard. This removes your account, routines, checklist history, settings, account-linked prayer-time cache, and authentication tokens. Anonymous aggregate analytics counts may remain because they contain no account ID or content and cannot be connected back to the deleted account.</p><p>If you cannot access your account, request deletion by emailing <a className="font-semibold text-career underline" href="mailto:privacy@daycraft.app">privacy@daycraft.app</a>. <strong>This is a provisional placeholder contact address and must be replaced with a monitored address before public launch.</strong> Daycraft may need to verify that you own the account before acting on a request.</p></Section>
  <Section title="Security and your choices"><p>Daycraft uses hashed passwords, email verification, expiring reset links, OAuth state validation, account-scoped database queries, and encrypted HTTPS in a proper production deployment. No online service can promise perfect security.</p><p>You may decline location access; the rest of the planner remains usable, and prayer times may use configured fallback coordinates or be unavailable. You may also choose password sign-in instead of Google sign-in.</p></Section>
  <Section title="Changes"><p>If this policy changes materially, Daycraft will provide reasonable notice through the app or account email before the change takes effect when practical.</p></Section>
</LegalShell>}

export function TermsPage(){return <LegalShell title="Terms of Service" updated="Last updated: August 5, 2026">
  <p>These Terms govern your use of Daycraft. By creating an account or continuing with Google, you agree to them.</p>
  <Section title="Using Daycraft"><p>You may use Daycraft to create and follow personal routines and habits. You are responsible for providing accurate account information, keeping your credentials and devices secure, and promptly resetting your password if you suspect unauthorized access.</p></Section>
  <Section title="Acceptable use"><p>Do not use Daycraft to break the law, harm others, probe or disrupt the service, bypass access controls, upload malicious material, scrape the service at scale, impersonate another person, or resell Daycraft or its data without written permission. Reasonable personal use and ordinary integrations with your own account are welcome.</p></Section>
  <Section title="Your content"><p>You retain ownership of the routine and checklist content you create. You give Daycraft permission to store, process, and display that content only as needed to operate and improve the service. You are responsible for content you enter.</p></Section>
  <Section title="Service availability and changes"><p>Daycraft is an early-stage service provided on an “as is” and “as available” basis. Features may contain errors or experience interruptions. Daycraft may modify or discontinue features or the service, with reasonable notice for material changes when practical. No promise is made that the service will always be available or that data can always be recovered, so keep separate copies of information you cannot afford to lose.</p></Section>
  <Section title="Not professional or safety-critical advice"><p>Daycraft is a personal-productivity tool. It does not provide medical, mental-health, financial, legal, emergency, or other professional advice and should not be used for safety-critical decisions.</p><p>Prayer times are supplied for convenience through a third-party API and may be inaccurate because of location, calculation method, network failures, or local practice. Verify prayer times with an authoritative local source when timing matters for religious observance.</p></Section>
  <Section title="Account suspension and termination"><p>You may delete your account at any time. Daycraft may restrict or terminate an account that materially violates these Terms, threatens the service, or creates legal risk. When practical, reasonable notice and an opportunity to correct the issue will be provided.</p></Section>
  <Section title="Limitation of liability"><p>To the fullest extent allowed by applicable law, Daycraft and its operator are not liable for indirect, incidental, special, consequential, or lost-profit damages, or for losses caused by relying on schedules, reminders, prayer times, or unavailable data. For a free early-stage service, total liability for claims related to Daycraft will not exceed the amount you paid for the service during the previous twelve months, which may be zero.</p><p>Some laws do not allow certain exclusions or limits, so these limitations apply only as far as the law permits. Nothing here excludes liability that cannot legally be excluded.</p></Section>
  <Section title="Changes to these Terms"><p>Daycraft may update these Terms as the product evolves. Material changes will receive reasonable notice through the app or account email when practical. Continuing to use Daycraft after the effective date means you accept the updated Terms.</p></Section>
  <Section title="Contact"><p>Questions may be sent to <a className="font-semibold text-career underline" href="mailto:privacy@daycraft.app">privacy@daycraft.app</a>. <strong>This is a provisional placeholder address that must be replaced with a monitored contact before public launch.</strong></p></Section>
</LegalShell>}

function LegalShell({title,updated,children}){return <div className="min-h-screen bg-cream px-4 py-8 text-ink sm:px-6 sm:py-12"><header className="mx-auto flex max-w-3xl items-center justify-between gap-4"><Link to="/" className="display-title text-3xl sm:text-4xl">Daycraft</Link><Link to="/register" className="inline-flex min-h-touch items-center rounded-xl bg-ink px-4 font-sans text-sm font-bold text-white">Create account</Link></header><main className="mx-auto mt-8 max-w-3xl rounded-card bg-paper px-5 py-7 shadow-card ring-1 ring-black/10 sm:px-10 sm:py-10"><p className="eyebrow text-career">Daycraft trust center</p><h1 className="mt-3 display-title text-4xl sm:text-5xl">{title}</h1><p className="mt-2 font-sans text-xs text-ink/45">{updated}</p><div className="mt-7 font-sans text-body leading-7 text-ink/70 sm:text-base sm:leading-8">{children}</div><div className="mt-10 rounded-2xl bg-cream/70 p-4 font-sans text-sm leading-6 text-ink/60 ring-1 ring-black/[.06]">This document is an honest first draft for an early-stage product. It is not legal advice or a substitute for review by a qualified lawyer before commercial launch or meaningful public use.</div></main><div className="mx-auto max-w-3xl"><PublicFooter/></div></div>}
