import { useState } from 'react'
import { Plus, Trash2 } from 'lucide-react'
import { CATEGORY_KEYS } from '../config/categories.js'
const input='min-h-touch rounded-xl bg-white px-3 font-sans text-sm ring-1 ring-black/15 focus:outline-none focus-visible:ring-2 focus-visible:ring-career'
export default function GroupManagePanel({ group, onUpdate, onAddEntry, onAddItem, onDelete }) {
  const [name,setName]=useState(group.name); const [color,setColor]=useState(group.color); const [weekdays,setWeekdays]=useState(group.weekdays); const [entry,setEntry]=useState({start:'09:00',end:'10:00',description:'',category:'Life'}); const [label,setLabel]=useState(''); const [busy,setBusy]=useState(false)
  const saveGroup=async()=>{if(!weekdays.length)return;setBusy(true);await onUpdate({name:name.trim(),color,weekdays});setBusy(false)}
  return <section className="mt-5 rounded-card bg-paper p-5 ring-1 ring-black/10" aria-label="Manage day group">
    <h2 className="font-sans text-base font-bold">Routine settings</h2>
    <div className="mt-3 grid gap-2 sm:grid-cols-[1fr_120px_auto]"><input aria-label="Group name" value={name} onChange={e=>setName(e.target.value)} className={input}/><input aria-label="Group color" type="color" value={color} onChange={e=>setColor(e.target.value)} className={`${input} w-full p-1`}/><button disabled={busy||!name.trim()||!weekdays.length} onClick={saveGroup} className="min-h-touch rounded-xl bg-ink px-4 font-sans text-sm font-bold text-white disabled:opacity-50">{busy?'Saving…':'Save group'}</button></div>
    <fieldset className="mt-3"><legend className="font-sans text-xs font-bold uppercase tracking-wide text-ink/55">Repeats on</legend><div className="mt-2 grid grid-cols-4 gap-2 sm:grid-cols-7">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((d,i)=><button key={d} type="button" aria-pressed={weekdays.includes(i)} onClick={()=>setWeekdays(v=>v.includes(i)?v.filter(x=>x!==i):[...v,i])} className="min-h-touch rounded-xl font-sans text-xs font-bold ring-1 ring-black/15" style={weekdays.includes(i)?{backgroundColor:color,color:'#fff'}:{}}>{d}</button>)}</div>{!weekdays.length&&<p className="mt-2 font-sans text-xs font-semibold text-language">Choose at least one weekday.</p>}</fieldset>
    <div className="mt-5 grid gap-4 lg:grid-cols-2"><form onSubmit={async e=>{e.preventDefault();if(!entry.description.trim())return;setBusy(true);await onAddEntry(entry);setEntry({...entry,description:''});setBusy(false)}} className="rounded-2xl bg-cream/60 p-4"><h3 className="font-sans text-sm font-bold">Add schedule block</h3><div className="mt-3 grid grid-cols-2 gap-2"><input aria-label="Start time" type="time" value={entry.start} onChange={e=>setEntry({...entry,start:e.target.value})} className={input}/><input aria-label="End time" type="time" value={entry.end} onChange={e=>setEntry({...entry,end:e.target.value})} className={input}/><input aria-label="Description" placeholder="Description" value={entry.description} onChange={e=>setEntry({...entry,description:e.target.value})} className={`${input} col-span-2`}/><select aria-label="Category" value={entry.category} onChange={e=>setEntry({...entry,category:e.target.value})} className={input}>{CATEGORY_KEYS.map(k=><option key={k}>{k}</option>)}</select><button disabled={busy} className="flex min-h-touch items-center justify-center gap-1 rounded-xl bg-ink px-3 font-sans text-sm font-bold text-white"><Plus className="h-4 w-4"/>Add</button></div></form>
      <form onSubmit={async e=>{e.preventDefault();if(!label.trim())return;setBusy(true);await onAddItem(label.trim());setLabel('');setBusy(false)}} className="rounded-2xl bg-cream/60 p-4"><h3 className="font-sans text-sm font-bold">Add checklist item</h3><div className="mt-3 flex gap-2"><input aria-label="Checklist label" placeholder="New habit" value={label} onChange={e=>setLabel(e.target.value)} className={`${input} min-w-0 flex-1`}/><button disabled={busy} className="flex min-h-touch items-center gap-1 rounded-xl bg-ink px-3 font-sans text-sm font-bold text-white"><Plus className="h-4 w-4"/>Add</button></div></form></div>
    <div className="mt-5 border-t border-black/10 pt-4 text-right"><button type="button" onClick={onDelete} className="inline-flex min-h-touch items-center gap-2 rounded-xl px-4 font-sans text-sm font-bold text-language ring-1 ring-language/30"><Trash2 className="h-4 w-4"/>Delete this group</button></div>
  </section>
}
